spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:

  flyway:
    enabled: true
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    user: sa
    password:
    locations: classpath:db/migration, classpath:db/test-data
    placeholders:
      authorsFullTextIndexes: ""
      articlesFullTextIndexes: ""
      usersEmailConstraint: CONSTRAINT chk_email_format CHECK (email LIKE '%@%.%'),