spring:
  config:
    import: classpath:database.yml
  profiles:
    active:
      - test

  datasource:
    url: jdbc:mysql://localhost:3306/${com.prod.database}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: ${com.username}
    password: ${com.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  r2dbc:
    url: r2dbc:mysql://localhost:3306/${com.prod.database}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: ${com.username}
    password: ${com.password}
    name: ${com.prod.database}

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
